# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: R
dist: trusty
sudo: required
warnings_are_errors: false
cache: packages

before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update -q; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install g++-4.9 -y; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 100; fi

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libgmp3-dev
      
after_success:
    - Rscript -e "covr::codecov()"
    
repos:
  CRAN: http://cran.rstudio.com
