# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: R
warnings_are_errors: false

matrix:
  include:
    - os: osx
      sudo: required
      r:
        - oldrel
        - release
        - devel

addons:
  apt:
    packages:
      - libgmp3-dev
      
after_success:
    - Rscript -e "covr::codecov(line_exclusions = c('inst/include/libdivide.h', 'inst/include/CleanConvert.h', 'R/zzz.R'))"
    
repos:
  CRAN: http://cran.rstudio.com
