# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: R
dist: trusty
sudo: required
warnings_are_errors: false
cache: packages

before_install:
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-6
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - libgmp3-dev
      
after_success:
    - Rscript -e "covr::codecov()"
