# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: R
warnings_are_errors: false

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      r: release
    - os: linux
      dist: trusty
      sudo: required
      r: devel
    - os: osx
      sudo: required
      r: release
      
env:
  global:
    - DOCKER_OPTS="--rm -ti -v $(pwd):/mnt -w /mnt"
      DOCKER_CNTR="rcpp/ci"
      R_BLD_OPTS="--no-build-vignettes --no-manual"
      R_CHK_OPTS="--no-vignettes --no-manual"
       
before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update -q; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install g++-4.9 -y; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 100; fi
  - docker pull ${DOCKER_CNTR}
  - docker run ${DOCKER_OPTS} ${DOCKER_CNTR} r -p -e 'sessionInfo()'
  
install:
  - docker run ${DOCKER_OPTS} ${DOCKER_CNTR} R CMD build ${R_BLD_OPTS} .

script:
  - docker run ${DOCKER_OPTS} ${DOCKER_CNTR} R CMD check ${R_CHK_OPTS} Rcpp_*.tar.gz

addons:
  apt:
    packages:
      - libgmp3-dev
      
r_packages:
  - Rcpp
  - gmp
  - numbers
  - RcppThread
  - devtools
  - testthat
  - microbenchmark
      
after_success:
    - Rscript -e "covr::codecov(line_exclusions = c('inst/include/libdivide.h', 'inst/include/CleanConvert.h', 'R/zzz.R'))"
    
repos:
  CRAN: http://cran.rstudio.com
