# Generated by cpp11: do not edit by hand

ComboGridCpp <- function(RList, RIsRep) {
  .Call(`_RcppAlgos_ComboGridCpp`, RList, RIsRep)
}

CheckConstrndCpp <- function(RCnstrntFun, RCompFun, Rtarget) {
  .Call(`_RcppAlgos_CheckConstrndCpp`, RCnstrntFun, RCompFun, Rtarget)
}

CheckReturn <- function(Rv, RCnstrntFun, RCompFun, Rtarget, RKeepRes, stdFun) {
  .Call(`_RcppAlgos_CheckReturn`, Rv, RCnstrntFun, RCompFun, Rtarget, RKeepRes, stdFun)
}

CombinatoricsApply <- function(Rv, Rm, RisRep, RFreqs, Rlow, Rhigh, stdFun, myEnv, RFunVal, RIsComb) {
  .Call(`_RcppAlgos_CombinatoricsApply`, Rv, Rm, RisRep, RFreqs, Rlow, Rhigh, stdFun, myEnv, RFunVal, RIsComb)
}

CombinatoricsCount <- function(Rv, Rm, RisRep, RFreqs, RIsComb) {
  .Call(`_RcppAlgos_CombinatoricsCount`, Rv, Rm, RisRep, RFreqs, RIsComb)
}

PartitionsCount <- function(Rtarget, Rv, Rm, RisRep, RFreqs, RcompFun, Rlow, Rtolerance, RPartDesign, Rshow) {
  .Call(`_RcppAlgos_PartitionsCount`, Rtarget, Rv, Rm, RisRep, RFreqs, RcompFun, Rlow, Rtolerance, RPartDesign, Rshow)
}

ComboGroupsCountCpp <- function(Rv, RNumGroups) {
  .Call(`_RcppAlgos_ComboGroupsCountCpp`, Rv, RNumGroups)
}

CombinatoricsStndrd <- function(Rv, Rm, RisRep, RFreqs, Rlow, Rhigh, Rparallel, RNumThreads, RmaxThreads, RIsComb) {
  .Call(`_RcppAlgos_CombinatoricsStndrd`, Rv, Rm, RisRep, RFreqs, Rlow, Rhigh, Rparallel, RNumThreads, RmaxThreads, RIsComb)
}

ComboGroupsCpp <- function(Rv, RNumGroups, RRetType, Rlow, Rhigh, Rparallel, RNumThreads, RmaxThreads, RIsSample, RindexVec, RmySeed, RNumSamp, baseSample, RNamed, myEnv) {
  .Call(`_RcppAlgos_ComboGroupsCpp`, Rv, RNumGroups, RRetType, Rlow, Rhigh, Rparallel, RNumThreads, RmaxThreads, RIsSample, RindexVec, RmySeed, RNumSamp, baseSample, RNamed, myEnv)
}

CombinatoricsCnstrt <- function(Rv, Rm, RisRep, RFreqs, Rlow, Rhigh, RmainFun, RcompFun, Rtarget, RIsComb, RKeepRes, Rparallel, RnThreads, RmaxThreads, Rtolerance) {
  .Call(`_RcppAlgos_CombinatoricsCnstrt`, Rv, Rm, RisRep, RFreqs, Rlow, Rhigh, RmainFun, RcompFun, Rtarget, RIsComb, RKeepRes, Rparallel, RnThreads, RmaxThreads, Rtolerance)
}

DivNumSieveCpp <- function(Rb1, Rb2, RbDivSieve, RisNamed, RNumThreads, RmaxThreads) {
  .Call(`_RcppAlgos_DivNumSieveCpp`, Rb1, Rb2, RbDivSieve, RisNamed, RNumThreads, RmaxThreads)
}

CombClassNew <- function(RVals, RboolVec, freqInfo, Rparallel, RstdFun, Rrho, R_RFunVal, RmainFun, RcompFun, Rtarget, RKeepRes, Rtolerance, RmIsNull, RretVal) {
  .Call(`_RcppAlgos_CombClassNew`, RVals, RboolVec, freqInfo, Rparallel, RstdFun, Rrho, R_RFunVal, RmainFun, RcompFun, Rtarget, RKeepRes, Rtolerance, RmIsNull, RretVal)
}

StartOverGlue <- function(ext) {
  .Call(`_RcppAlgos_StartOverGlue`, ext)
}

NextCombGlue <- function(ext) {
  .Call(`_RcppAlgos_NextCombGlue`, ext)
}

NextNumCombGlue <- function(ext, Rnum) {
  .Call(`_RcppAlgos_NextNumCombGlue`, ext, Rnum)
}

NextGatherGlue <- function(ext) {
  .Call(`_RcppAlgos_NextGatherGlue`, ext)
}

PrevCombGlue <- function(ext) {
  .Call(`_RcppAlgos_PrevCombGlue`, ext)
}

PrevNumCombGlue <- function(ext, Rnum) {
  .Call(`_RcppAlgos_PrevNumCombGlue`, ext, Rnum)
}

PrevGatherGlue <- function(ext) {
  .Call(`_RcppAlgos_PrevGatherGlue`, ext)
}

CurrCombGlue <- function(ext) {
  .Call(`_RcppAlgos_CurrCombGlue`, ext)
}

RandomAccessGlue <- function(ext, RIndexVec) {
  .Call(`_RcppAlgos_RandomAccessGlue`, ext, RIndexVec)
}

SourceVectorGlue <- function(ext) {
  .Call(`_RcppAlgos_SourceVectorGlue`, ext)
}

FrontGlue <- function(ext) {
  .Call(`_RcppAlgos_FrontGlue`, ext)
}

BackGlue <- function(ext) {
  .Call(`_RcppAlgos_BackGlue`, ext)
}

SummaryGlue <- function(ext) {
  .Call(`_RcppAlgos_SummaryGlue`, ext)
}

GetClassVals <- function(Rv, Rm, RisRep, RFreqs, RIsComb, stdFun, RThreads, RmaxThreads, RIsCnstrd) {
  .Call(`_RcppAlgos_GetClassVals`, Rv, Rm, RisRep, RFreqs, RIsComb, stdFun, RThreads, RmaxThreads, RIsCnstrd)
}

MotleyContainer <- function(Rb1, Rb2, RIsEuler, RNamed, RNumThreads, RmaxThreads) {
  .Call(`_RcppAlgos_MotleyContainer`, Rb1, Rb2, RIsEuler, RNamed, RNumThreads, RmaxThreads)
}

cpp11GetNumThreads <- function() {
  .Call(`_RcppAlgos_cpp11GetNumThreads`)
}

PollardRhoContainer <- function(Rv, RNamed, RbPrimeFacs, RbAllFacs, RNumThreads, RmaxThreads) {
  .Call(`_RcppAlgos_PollardRhoContainer`, Rv, RNamed, RbPrimeFacs, RbAllFacs, RNumThreads, RmaxThreads)
}

PrimeCountCpp <- function(Rn, RNumThreads, RmaxThreads) {
  .Call(`_RcppAlgos_PrimeCountCpp`, Rn, RNumThreads, RmaxThreads)
}

PrimeSieveCpp <- function(Rb1, Rb2, RNumThreads, RmaxCores, RmaxThreads) {
  .Call(`_RcppAlgos_PrimeSieveCpp`, Rb1, Rb2, RNumThreads, RmaxCores, RmaxThreads)
}

SampleCombPerm <- function(Rv, Rm, RisRep, RFreqs, RindexVec, RIsComb, RmySeed, RNumSamp, baseSample, stdFun, myEnv, Rparallel, RNumThreads, RmaxThreads, RNamed, RFunVal) {
  .Call(`_RcppAlgos_SampleCombPerm`, Rv, Rm, RisRep, RFreqs, RindexVec, RIsComb, RmySeed, RNumSamp, baseSample, stdFun, myEnv, Rparallel, RNumThreads, RmaxThreads, RNamed, RFunVal)
}

SamplePartitions <- function(Rv, Rm, RisRep, RFreqs, RindexVec, RmySeed, RNumSamp, baseSample, Rparallel, RNumThreads, RmaxThreads, RNamed, RcompFun, Rtarget, Rtolerance, myEnv) {
  .Call(`_RcppAlgos_SamplePartitions`, Rv, Rm, RisRep, RFreqs, RindexVec, RmySeed, RNumSamp, baseSample, Rparallel, RNumThreads, RmaxThreads, RNamed, RcompFun, Rtarget, Rtolerance, myEnv)
}
