# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ComboRcpp <- function(Rv, Rm, Rrep, fun1, fun2, lim, numRow) {
    .Call(`_RcppAlgos_ComboRcpp`, Rv, Rm, Rrep, fun1, fun2, lim, numRow)
}

NumDivisorsSieve <- function(n) {
    .Call(`_RcppAlgos_NumDivisorsSieve`, n)
}

DivisorListRcpp <- function(n) {
    .Call(`_RcppAlgos_DivisorListRcpp`, n)
}

PrimeFactorizationListRcpp <- function(n) {
    .Call(`_RcppAlgos_PrimeFactorizationListRcpp`, n)
}

EulerPhiSieveRcpp <- function(n) {
    .Call(`_RcppAlgos_EulerPhiSieveRcpp`, n)
}

EratosthenesRcpp <- function(Rb1, Rb2) {
    .Call(`_RcppAlgos_EratosthenesRcpp`, Rb1, Rb2)
}

