# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CombinatoricsRcpp <- function(Rv, Rm, Rrepetition, f1, f2, lim, numRow, RIsComb, RIsFactor, RKeepRes) {
    .Call(`_RcppAlgos_CombinatoricsRcpp`, Rv, Rm, Rrepetition, f1, f2, lim, numRow, RIsComb, RIsFactor, RKeepRes)
}

NumDivisorsSieve <- function(n) {
    .Call(`_RcppAlgos_NumDivisorsSieve`, n)
}

DivisorListRcpp <- function(n) {
    .Call(`_RcppAlgos_DivisorListRcpp`, n)
}

PermsRepLenRcpp <- function(Rv, Rm, RIsFactor) {
    .Call(`_RcppAlgos_PermsRepLenRcpp`, Rv, Rm, RIsFactor)
}

PrimeFactorizationListRcpp <- function(n) {
    .Call(`_RcppAlgos_PrimeFactorizationListRcpp`, n)
}

EulerPhiSieveRcpp <- function(n) {
    .Call(`_RcppAlgos_EulerPhiSieveRcpp`, n)
}

EratosthenesRcpp <- function(Rb1, Rb2) {
    .Call(`_RcppAlgos_EratosthenesRcpp`, Rb1, Rb2)
}

