# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ComboRcpp <- function(Rn, Rr, Rv, Rrep, fun1, fun2, lim, numRow) {
    .Call(`_algosRcpp_ComboRcpp`, Rn, Rr, Rv, Rrep, fun1, fun2, lim, numRow)
}

NumDivisorsSieve <- function(n) {
    .Call(`_algosRcpp_NumDivisorsSieve`, n)
}

DivisorListRcpp <- function(n) {
    .Call(`_algosRcpp_DivisorListRcpp`, n)
}

PrimeFactorizationListRcpp <- function(n) {
    .Call(`_algosRcpp_PrimeFactorizationListRcpp`, n)
}

EulerPhiSieveRcpp <- function(n) {
    .Call(`_algosRcpp_EulerPhiSieveRcpp`, n)
}

EratosthenesRcpp <- function(Rb1, Rb2) {
    .Call(`_algosRcpp_EratosthenesRcpp`, Rb1, Rb2)
}

